# Generated by Django 6.0.4 on 2026-04-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='id_document_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_id_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university',
        ),
    ]
