# Generated by ChatGPT on 2026-04-18

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


def backfill_room_participants(apps, schema_editor):
    ChatRoom = apps.get_model("chat", "ChatRoom")
    Message = apps.get_model("chat", "Message")
    VendorProfile = apps.get_model("vendors", "VendorProfile")

    for room in ChatRoom.objects.all().iterator():
        participants = list(room.participants.all())
        buyer_user = next((u for u in participants if getattr(u, "role", None) == "student"), None)
        vendor_user = next((u for u in participants if getattr(u, "role", None) == "vendor"), None)

        if not buyer_user or not vendor_user:
            Message.objects.filter(room_id=room.id).delete()
            room.delete()
            continue

        vendor_profile = VendorProfile.objects.filter(user_id=vendor_user.id).first()
        if not vendor_profile:
            Message.objects.filter(room_id=room.id).delete()
            room.delete()
            continue

        room.buyer_id = buyer_user.id
        room.vendor_id = vendor_profile.id
        room.save(update_fields=["buyer", "vendor"])

    # Deduplicate by (buyer, vendor, product) before unique constraint is added.
    canonical_by_key = {}
    for room in ChatRoom.objects.exclude(buyer_id__isnull=True).exclude(vendor_id__isnull=True).order_by("created_at", "id"):
        key = (room.buyer_id, room.vendor_id, room.product_id)
        canonical_room_id = canonical_by_key.get(key)
        if canonical_room_id is None:
            canonical_by_key[key] = room.id
            continue

        Message.objects.filter(room_id=room.id).update(room_id=canonical_room_id)
        room.delete()


def noop_reverse(apps, schema_editor):
    # Irreversible due to data consolidation and role-derived mapping.
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0001_initial"),
        ("products", "0003_productimage_cloudinary_public_id"),
        ("vendors", "0002_remove_vendorprofile_banner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_rooms",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_chat_rooms",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.RunPython(backfill_room_participants, noop_reverse),
        migrations.AlterField(
            model_name="chatroom",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_chat_rooms",
                to="vendors.vendorprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("buyer", "vendor", "product"),
                condition=models.Q(product__isnull=False),
                name="uniq_chatroom_buyer_vendor_product_non_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(
                fields=("buyer", "vendor"),
                condition=models.Q(product__isnull=True),
                name="uniq_chatroom_buyer_vendor_when_product_null",
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["buyer", "created_at"], name="idx_chatroom_buyer_created"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["vendor", "created_at"], name="idx_chatroom_vendor_created"),
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="participants",
        ),
        migrations.RenameModel(
            old_name="Message",
            new_name="ChatMessage",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="content",
            new_name="message",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="created_at",
            new_name="sent_at",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["sent_at"]},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["room", "sent_at"], name="idx_chatmessage_room_sent"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["room", "is_read"], name="idx_chatmessage_room_read"),
        ),
    ]
