# Generated by Django 6.0.4 on 2026-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('sslcommerz', 'SSLCommerz')], max_length=15),
        ),
    ]
