# Generated by Django 6.0.4 on 2026-04-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_alter_order_status_vendororder_and_more'),
        ('payments', '0002_payment_callback_received_at_payment_failure_reason_and_more'),
        ('vendors', '0002_remove_vendorprofile_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=200)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payouts', to='payments.payment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendorprofile')),
                ('vendor_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payout', to='orders.vendororder')),
            ],
            options={
                'db_table': 'vendor_payouts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'vendor_order'), name='uniq_vendor_payout_per_payment_vendor_order')],
            },
        ),
    ]
