# Generated by Django 6.0.4 on 2026-04-13 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_alter_order_status_vendororder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='orders.order')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='orders.vendororder')),
            ],
            options={
                'db_table': 'domain_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='idx_domain_event_type_status'), models.Index(fields=['status', 'created_at'], name='idx_dm_evt_stat_created')],
            },
        ),
    ]
