# Generated by Django 6.0.4 on 2026-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_domainevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(checkout_request_id__isnull=False),
                fields=("buyer", "checkout_request_id"),
                name="uniq_order_checkout_req_per_buyer",
            ),
        ),
    ]
