# Generated by Django 6.0.4 on 2026-04-13 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_checkout_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEventAdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('retry_single', 'Retry Single'), ('retry_bulk', 'Retry Bulk'), ('retry_bulk_dry_run', 'Retry Bulk Dry Run')], max_length=30)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_event_admin_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain_event_admin_audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='idx_dm_evt_ad_act_created'), models.Index(fields=['actor', 'created_at'], name='idx_dm_evt_ad_actor_created')],
            },
        ),
    ]
