# Generated by Django 6.0.4 on 2026-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='idx_order_buyer_created',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='idx_order_item_order_product',
        ),
    ]
