# Generated by Django 6.0.3 on 2026-03-05 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default='10.00', help_text='Platform commission percentage charged on each sale.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
