# Generated by Django 6.0.4 on 2026-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='idx_cart_user',
        ),
    ]
