# Generated by Django 6.0.3 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_producttag_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
