# Generated by Django 6.0.3 on 2026-04-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage_cloudinary_public_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductViewDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("view_date", models.DateField(db_index=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_view_daily",
                "ordering": ["-view_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="productviewdaily",
            constraint=models.UniqueConstraint(fields=("product", "view_date"), name="uniq_product_daily_view"),
        ),
    ]
