# Generated by Django 6.0.4 on 2026-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_perf_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_status_created',
        ),
    ]
